[build]

app = "recepcionista-ai-bot"
primary_region = "mia"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    path = "/qr"

[mounts]
  source = "auth_data"
  destination = "/app/auth_session"
